-- Create historical prices table
CREATE TABLE IF NOT EXISTS historical_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    price NUMERIC NOT NULL,
    change_percentage NUMERIC,
    is_market_hours BOOLEAN DEFAULT false,
    name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    -- Add a unique constraint to prevent duplicate entries for the same symbol and timestamp
    UNIQUE(symbol, timestamp)
);

-- Create indexes for efficient querying
CREATE INDEX idx_historical_prices_symbol ON historical_prices(symbol);
CREATE INDEX idx_historical_prices_timestamp ON historical_prices(timestamp);
CREATE INDEX idx_historical_prices_symbol_timestamp ON historical_prices(symbol, timestamp);

-- Enable Row Level Security
ALTER TABLE historical_prices ENABLE ROW LEVEL SECURITY;

-- Create policy for read access (anyone can read)
CREATE POLICY "Anyone can read historical prices"
ON historical_prices FOR SELECT
USING (true);

-- Create policy for insert (only authenticated service can insert)
CREATE POLICY "Only service can insert historical prices"
ON historical_prices FOR INSERT
WITH CHECK (auth.role() = 'service');

-- Create policy for delete (only service can delete)
CREATE POLICY "Only service can delete historical prices"
ON historical_prices FOR DELETE
USING (auth.role() = 'service');

-- Create function to clean up old data
-- Retains 5 years of historical data for long-term analysis
CREATE OR REPLACE FUNCTION cleanup_historical_prices()
RETURNS void AS $$
BEGIN
    -- Delete data older than 5 years
    DELETE FROM historical_prices
    WHERE timestamp < NOW() - INTERVAL '5 years';
END;
$$ LANGUAGE plpgsql; 